
service: cadastro-paciente
frameworkVersion: '3'

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x

  stage: dev
  region: us-east-1

  iamRoleStatements:
    - Effect: Allow
      Action: 
        - dynamodb:Query
        - dynamodb:Scane
        - dynamodb:PutItem
        - dynamodb:DeleteItem
      Resource: 
  
 arn:aws:sts::160861998468:assumed-role/cadastro-paciente-dev-us-east-1-lambdaRole/cadastro-paciente-dev-listarPacientes : arn:aws:dynamodb:us-east-1:160861998468:table/PACIENTES because no identity-based policy allows the dynamodb:Scan action"
}

functions:
  listarPacientes:
    handler: handler.listarPacientes
    events:
      - http:
          path: pacientes
          method: get 

  obterPaciente:
    handler: handler.obterPaciente
    events:
      - http:
          path: pacientes/{pacienteId}
          method: get 

resources:
  Resources:
    PacientesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: PACIENTES
        AttributeDefinitions:
          - AttributeName: paciente_id
            AttributeType: S
        KeySchema:
          - AttributeName: paciente_id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
